version: '3'
services:
  asterisk:
    image: blup1980/asterisk  
    ports:
     - "10000-10500:10000-10500"
     - "5060:5060"
    entrypoint: asterisk -cvvv
    volumes:
        - ./etc/asterisk:/etc/asterisk
        - ./sounds:/var/lib/asterisk/sounds
    stdin_open: true
    tty: true
