version: '3'
services:
  asterisk:
    image: blup1980/asterisk:20.4  
    ports:
     - "10000-10500:10000-10500"
     - "5060:5060"
    entrypoint: asterisk -cvvv
    volumes:
        - asteriskConf:/etc/asterisk

    stdin_open: true
    tty: true

volumes:
    asteriskConf:
        external: true
